### ISSUE TITLE
getting this out of memory error

### ISSUE THREAD

**Issue by Pr0xyblade** [PhoenixMinerDevTeam/PhoenixMiner#12]
Hi all, im trying to mine ETH with a 1050 Ti, and after doing the config and launching phoenixminer, I get this: 
![image](https://user-images.githubusercontent.com/72248782/111851351-b4101b00-8977-11eb-9afb-ad54b92b0b29.png)

**Comment by PhoenixMinerDevTeam** [comment]
You need at least 4.16 GB, and your card has a total of 4 GB, with only 3.30 GB free. You can't mine ETH with this card, only something like ETC, or some other coin with lower DAG size
