### ISSUE TITLE
Invalid Share Command-line argument

### ISSUE THREAD

**Issue by SkillTim** [PhoenixMinerDevTeam/PhoenixMiner#13]
I'd like a new Command-line argument that reports on Invalid shares. I was thinking something like this. When more than one invalid share is detected in a 24h period by an instance of Phoenix Miner, the user would be notified (e.g. by email) that GPU1 on -wal X.Rig had reported invalid shares.

**Comment by PhoenixMinerDevTeam** [comment]
The more appropriate "home" for such feature is at an external tool that monitors the miner via the remote status and control API on port 3333. The API provides the invalid shares for all GPUs and many additional information like temperatures, fan speeds, etc.
