### ISSUE TITLE
On GPU crash overclocks aren't reset causing -mcdag to be ineffective 

### ISSUE THREAD

**Issue by deadpuck** [PhoenixMinerDevTeam/PhoenixMiner#15]
I know this wont be a problem for most but I mine on a 3060ti and a 1070 both are overclocked through Phoenix miner so I can make use of -mcdag 1 allowing delayed memory overclock. Sadly every now and then since I use the computer while I'm mining on it my 1070 will crash causing Phoenix miner to restart and the DAG to be loaded new for both cards. My issue is that when Phoenix miner crashes it doesn't reset OC to stock. Possible fix would be to add a feature that on crash OC gets reset to stock or more preferably a command line argument that would allow for as the miner starts to set all OC to stock before trying to overclock from Phoenix miner.

**Comment by PhoenixMinerDevTeam** [comment]
Try the following command-line option:

`-resetoc`
   Reset the HW overclocking settings on startup

**Comment by deadpuck** [comment]
Thank you so much, i was looking under the Hardware control options of the command line arguments section so i didnt notice it before! i appreciate the help even though it feels like dumb question now haha
