### ISSUE TITLE
happens-spontaneous switching to other pools!!!

### ISSUE THREAD

**Issue by EVGENY1777** [PhoenixMinerDevTeam/PhoenixMiner#19]
Hello!  
I use Phoenix 5.5 on the pool eu1. nethermine. org:4444.  
But very often this happens-spontaneous switching to other pools:  
eu.emc. io:7878  
gate.io 
nanopool
Why is this happening and what to do so that the miner does not switch to the pool, 
with the exception of
specified in the bat file? 
Below is today's log.  
With respect. 
-------------------------------------------
Log PhoenixMiner 5.5c 23.03.2021: (Full version)
https://transfiles.ru/1qyws
----------------------------------
2021.03.23:11:27:20.931: main Phoenix Miner 5.5c Windows/msvc - Release build
2021.03.23:11:27:20.931: main Cmd line: -pool eu1.ethermine.org:4444 -wal 0x47Bd9c56DBBe7C69cf26890e81096C8c65574661 -worker h81 -rxboost 1 -gt 60 -epsw x -mode 1 -log 1 -mport 0 -etha 0 -ftime 55 -retrydelay 1 -tstop 89 -tstart 80 -coin eth 
2021.03.23:11:27:20.932: main No CUDA driver found
2021.03.23:11:27:23.995: main OpenCL driver version: 20.7-10/20.11.1
2021.03.23:11:27:24.040: main Available GPUs for mining:
2021.03.23:11:27:24.040: main GPU1: Radeon RX 580 Series (pcie 1), OpenCL 2.0, 8 GB VRAM, 36 CUs
2021.03.23:11:27:24.040: main GPU2: Radeon RX 580 Series (pcie 2), OpenCL 2.0, 8 GB VRAM, 36 CUs
2021.03.23:11:27:24.040: main GPU3: Radeon RX 580 Series (pcie 3), OpenCL 2.0, 8 GB VRAM, 36 CUs
2021.03.23:11:27:24.040: main GPU4: Radeon RX 580 Series (pcie 4), OpenCL 2.0, 8 GB VRAM, 36 CUs
2021.03.23:11:27:24.040: main GPU5: Radeon RX 580 Series (pcie 5), OpenCL 2.0, 8 GB VRAM, 36 CUs
2021.03.23:11:27:24.040: main GPU6: Radeon RX 580 Series (pcie 6), OpenCL 2.0, 8 GB VRAM, 36 CUs
---------------------------------------
2021.03.23:11:31:59.259: main Eth speed: 196.844 MH/s, shares: 7/0/0, time: 0:04
2021.03.23:11:31:59.259: main GPUs: 1: 32.790 MH/s (1) 2: 32.705 MH/s (1) 3: 31.810 MH/s (1) 4: 33.176 MH/s (2) 5: 33.179 MH/s (1) 6: 33.185 MH/s (1)
2021.03.23:11:32:04.328: eths Eth: Received: {"id": 0, "jsonrpc": "2.0", "result": ["0xacc154119fd8531306303c101134159e0ed6442a46b9cf5d9f2b2df30a5b4c09", "0x7aa37edf8729133537bc12e08304d81ec2d541fdcdd579647ed3daeb0763d30c", "0x00000000b7407f019e4630000000000000000000000000000000000000000000"]}
2021.03.23:11:32:04.328: eths Eth: New job #acc15411 from eu.emcd.io:7878; diff: 6000MH
2021.03.23:11:32:04.372: main Eth speed: 196.830 MH/s, shares: 7/0/0, time: 0:04
2021.03.23:11:32:04.372: main GPUs: 1: 32.771 MH/s (1) 2: 32.681 MH/s (1) 3: 31.813 MH/s (1) 4: 33.183 MH/s (2) 5: 33.190 MH/s (1) 6: 33.193 MH/s (1)
2021.03.23:11:32:06.458: eths Eth: Send: {"id":5,"jsonrpc":"2.0","method":"eth_getWork","params":[]}

**Comment by PhoenixMinerDevTeam** [comment]
In the log you have posted you can see that one pool is loaded from the command line (eu1.ethermine.org:4444), and six pools are loaded from the `epools.txt` file. After failing to connect to the first pool, the miner tries to connect to the second one (the first one in `epools.txt`), and so on.

There is no default `epools.txt` file that is shipped with the miner (only an example file that is not used by PhoenixMiner unless you rename it to `epools.txt`), so you just need to delete the pools that you have added to `epools.txt` or change them to whatever you want.

Also, there are too much connection errors in the log file - you should check your network connection.
