### ISSUE TITLE
!!!Spontaneous switching of the miner to other pools and coins

### ISSUE THREAD

**Issue by EVGENY1777** [PhoenixMinerDevTeam/PhoenixMiner#22]
Today, two rigs were switched spontaneously -
one rig switched to ETC, 
the other to nanopool.  

What's going on???  
switched to TRM.... because this isn't the first time this has happened...
logs-below. 
https://transfiles.ru/dqax

**Comment by PhoenixMinerDevTeam** [comment]
Duplicate of issue #19
