### ISSUE TITLE
Phoenixh crash after last amd update

### ISSUE THREAD

**Issue by Gizmo648** [PhoenixMinerDevTeam/PhoenixMiner#23]
Phoenix crash after last update driver update 21.3.1

![IMG_2012](https://user-images.githubusercontent.com/25337476/112566831-53347880-8da5-11eb-8e55-837066566dd1.jpg)

**Comment by PhoenixMinerDevTeam** [comment]
PhoenixMiner 5.5c doesn't support the latest AMD Windows drivers 21.3.1, so you need to run older drivers (e.g. anything before 21.3.1 would work). If you see a yellow warning message `Unknown OpenCL driver version! Hashrate and stale shares may suffer` you need to install older driver.
