### ISSUE TITLE
RX 6800

### ISSUE THREAD

**Issue by ben1628** [PhoenixMinerDevTeam/PhoenixMiner#24]
I'm using RX 6800, I assume the miner can find that out and use the native kernel with RX 6800.

Or do I have to set it somehow?

**Comment by dau0815** [comment]
use older AMD driver ...

**Comment by ben1628** [comment]
What do you mean? 

I am using 20.11.2

**Comment by dau0815** [comment]
I read something about https://www.amd.com/en/support/kb/release-notes/rn-rad-win-21-1-1 is last supported good version for 6800XT, just try it.
