### ISSUE TITLE
Not mining on GTX 1660, GTX 1070

### ISSUE THREAD

**Issue by EqualCommon** [PhoenixMinerDevTeam/PhoenixMiner#36]
Trying to run phoenixminer in Windows 10 with two nvidia gpu's
 GTX 1660, GTX 1070

miner not start mining
standard batch files same behavior with eth and etc batch files.

log:
2021.04.03:23:32:01.526: main Phoenix Miner 5.5c Windows/msvc - Release build
2021.04.03:23:32:01.526: main Cmd line: -pool stratum1+tcp://eu.ezil.me:5555 -proto 2 -wal ETH.ZIL -worker RIG1 -nvidia -mode 0 -minRigSpeed 30 -wdog 1 -rmode 1 
2021.04.03:23:32:01.586: main CUDA version: 11.0, CUDA runtime: 8.0
2021.04.03:23:32:01.586: main Available GPUs for mining:
2021.04.03:23:32:01.586: main GPU1: NVIDIA GeForce GTX 1070 (pcie 33), CUDA cap. 6.1, 8 GB VRAM, 15 CUs
2021.04.03:23:32:01.586: main GPU2: NVIDIA GeForce GTX 1660 Ti (pcie 38), CUDA cap. 7.5, 6 GB VRAM, 24 CUs
end of log file

cuda 11
nvidia driver 465.89

**Comment by DeeDeeRanged** [comment]
Mixed CUDA drivers? Uninstall nvidia drivers completely with DDU utility reboot and reinstall the latest Nvidia drivers. Your problem is CUDA 11 and a CUDA 8.0 runtime, they should match at least on Linux it does.

**Comment by EqualCommon** [comment]
A fresh windows 10 without cuda is working good now. Thanks for your help
