### ISSUE TITLE
Rx 570 gpu driver version 20.11.1.. got incorrect share.. anyone can give me solution?

### ISSUE THREAD

**Issue by Saikatsaha1996** [PhoenixMinerDevTeam/PhoenixMiner#37]
![IMG_20210404_151836](https://user-images.githubusercontent.com/72664192/113505035-02b5db80-955a-11eb-838b-2b9151d35a42.jpg)

**Comment by DeeDeeRanged** [comment]
It happens sometimes. I have an RX 580 and I get 1 or 2 stale shares a day. If it happens continiously then there is something wrong. In your picture I also see a succesfull share.

**Comment by Saikatsaha1996** [comment]
> It happens sometimes. I have an RX 580 and I get 1 or 2 stale shares a day. If it happens continiously then there is something wrong. In your picture I also see a succesfull share.


Ok thank you... So much... 
No it not happen continue
I get every 24 hrs one or two invalid shares..
