### ISSUE TITLE
Auto-Tuning doesn't work

### ISSUE THREAD

**Issue by Avimarzan** [PhoenixMinerDevTeam/PhoenixMiner#42]
although i have -gt 0 in the config file the auto-tuning is not starting automatically

**Comment by PhoenixMinerDevTeam** [comment]
Auto-tune is supported only on AMD cards. It is also not supported if you are using the generic kernels (either by specifying `-clkernel` 0 or by using unsupported drivers - currently the latest AMD drivers 21.3.1, and 21.3.2 are not supported by PhoenixMiner 5.5c).

**Comment by Avimarzan** [comment]
I am currently using the last supported driver 2.1.1 as mention in the
release note without any value in -clkernel
but the auto-tune doesn't start automatically
once the miner is running I am able to start it by pressing z in the
console window
