### ISSUE TITLE
PLs HELP!! 

### ISSUE THREAD

**Issue by HiatoQuantico** [PhoenixMinerDevTeam/PhoenixMiner#44]
Help me fix this?
Unable to read pool response: Semaphore timeout has expired

[log20210409_115529.txt](https://github.com/PhoenixMinerDevTeam/PhoenixMiner/files/6286634/log20210409_115529.txt)

**Comment by HiatoQuantico** [comment]
https://github.com/ethereum-mining/ethminer/issues/1539
help me, is that it? But I don't know how to do this command, I wanted to study that too. Can someone help m
e?

**Comment by PhoenixMinerDevTeam** [comment]
Most probably a connectivity issue, or the pool has issues (overloaded, etc.) and is randomly disconnecting clients. The fact that it responded to one of the shares in your log after more than 70 seconds indicates that the pool is either overloaded, or having network issues itself.
