### ISSUE TITLE
rx 580 settings not holding

### ISSUE THREAD

**Issue by DeeDeeRanged** [PhoenixMinerDevTeam/PhoenixMiner#45]
Debian bullseye/testing with a XFX RX850 8GB videocard.
Starting PhoenixMiner with the following settings:
sudo PhoenixMiner -amd -hstats 5 -clKernel 0 -rxboost 1 -mclock 2000 -cclock 1100 -cvddc 900 -pool ssl://eu1.ethermine.org:5555 -wal <wallet>.rx580 -proto 3 -prate 0.0703

Bur for what reason I see this in the terminal
GPU1: 74C 55% 124W
GPU1: cclock 1366 MHz, cvddc 1112 mV,  mclock 2000 MHz
GPUs power: 124.2 W; cost: 0.21 USD/day

While I was expecting cclock 1100, cvddc 1100 mV, mclock 2000 MHz
Does that mean I have a locked vbios and therefore not able to change the settings?

**Comment by PhoenixMinerDevTeam** [comment]
In order to have working hardware control under Linux, PhoenixMiner must be running as root (`sudo ./PhoenixMiner ...`), AND you need to add the following boot parameter to the Linux kernel: `amdgpu.ppfeaturemask=0xffffffff`
