### ISSUE TITLE
An older release is marked latest

### ISSUE THREAD

**Issue by esskayesss** [PhoenixMinerDevTeam/PhoenixMiner#53]
SUPER SIMPLE ISSUE.
I was writing a package for the [AUR](https://aur.archlinux.org/packages/phoenixminer). I'm trying to use GitHub API to get a link to your latest release. I just noticed, an older release(5.4c) is marked as latest which is causing my package to fail. Please correct the release tags and help us people on ArchLinux to get your package installed even more easily. Thanks.

**Comment by PhoenixMinerDevTeam** [comment]
Will be corrected soon with the official release of 5.6c. The problem was caused by the rushed move to github, when we first uploaded 5.5c, and then 5.4c, which caused github to mark it as latest.
