### ISSUE TITLE
Remote control options (cdm) not working (v5.5c)

### ISSUE THREAD

**Issue by toxaco** [PhoenixMinerDevTeam/PhoenixMiner#63]
Using a TCP connection to pass this `{"id":0,"jsonrpc":"2.0","method":"miner_getstat1"}` `(Hex: 7b 22 69 64 22 3a 30 2c 22 6a 73 6f 6e 72 70 63 22 3a 22 32 2e 30 22 2c 22 6d 65 74 68 6f 64 22 3a 22 6d 69 6e 65 72 5f 67 65 74 73 74 61 74 31 22 7d )` (or any other "cdm" available options) does not return anything. 

I am using the settings described here: https://phoenixminer.org/documentation/arguments/#remote-control-options 

Here are the options I found for "cdm":

----------------
REQUEST:
{"id":0,"jsonrpc":"2.0","method":"miner_getstat1"}
 
RESPONSE:
{"result": ["9.3 - ETH", "21", "182724;51;0", "30502;30457;30297;30481;30479;30505", "0;0;0", "off;off;off;off;off;off", "53;71;57;67;61;72;55;70;59;71;61;70", "eth-eu1.nanopool.org:9999", "0;0;0;0"]}
"9.3 - ETH"				- miner version.
"21"					- running time, in minutes.
"182724"				- total ETH hashrate in MH/s, number of ETH shares, number of ETH rejected shares.
"30502;30457;30297;30481;30479;30505"	- detailed ETH hashrate for all GPUs.
"0;0;0"					- total DCR hashrate in MH/s, number of DCR shares, number of DCR rejected shares.
"off;off;off;off;off;off"		- detailed DCR hashrate for all GPUs.
"53;71;57;67;61;72;55;70;59;71;61;70"	- Temperature and Fan speed(%) pairs for all GPUs.
"eth-eu1.nanopool.org:9999"		- current mining pool. For dual mode, there will be two pools here.
"0;0;0;0"				- number of ETH invalid shares, number of ETH pool switches, number of DCR invalid shares, number of DCR pool switches.
 
COMMENTS:
Gets current statistics.
 
 
 
----------------
REQUEST:
 
{"id":0,"jsonrpc":"2.0","method":"miner_restart"}
 
RESPONSE:
none.
 
COMMENTS:
Restarts miner.
 
 
 
----------------
REQUEST:
{"id":0,"jsonrpc":"2.0","method":"miner_reboot"}
 
RESPONSE:
none.
 
COMMENTS:
Calls "reboot.bat" for Windows, or "reboot.bash" (or "reboot.sh") for Linux.
 
 
 
----------------
REQUEST:
{"id":0,"jsonrpc":"2.0","method":"control_gpu", "params":[0, 1]}
 
RESPONSE:
none.
 
COMMENTS:
first number - GPU index, or "-1" for all GPUs. Second number - new GPU state, 0 - disabled, 1 - ETH-only mode, 2 - dual mode.

**Comment by PhoenixMinerDevTeam** [comment]
You can find a more detailed description of the remote monitoring and control API here: https://github.com/PhoenixMinerDevTeam/PhoenixMiner/wiki/Remote-monitoring-and-control-API-for-PhoenixMiner

Most probably the problem is that you do not add new-line (\n) at the end of your request.
