### ISSUE TITLE
HOW, but, please, HOW do I remove -gt argument? 

### ISSUE THREAD

**Issue by pedrohrcunha** [PhoenixMinerDevTeam/PhoenixMiner#7]
I don't want PHOENIX MINER to AUTOTUNE my videocards. Can someone... HELP!?

**Comment by nihil5320** [comment]
Just set it manually, setting -gt x (where x is the desired gt value) will prevent autotuning.

**Comment by pedrohrcunha** [comment]
I don't understand what -gt (9 to 400 or whatev) does. It's very enigmatic. What's the point of setting this range without explaining it?

**Comment by leve1ord** [comment]
> I don't understand what -gt (9 to 400 or whatev) does. It's very enigmatic. What's the point of setting this range without explaining it?

You don't have to understand what -gt does. Start mining then press "z". Few minutes later when auto tune is done press "s" to see what -gt values is given to a gpu.
