### ISSUE TITLE
Readme still contains Mega link

### ISSUE THREAD

**Issue by vestigialdev** [PhoenixMinerDevTeam/PhoenixMiner#9]
Download and install
====================

You can download PhoenixMiner 5.5c from here:

https://mega.nz/#F!2VskDJrI!lsQsz1CdDe8x5cH3L8QaBw (MEGA)

**Comment by PhoenixMinerDevTeam** [comment]
Will be fixed in the next release - we can't change the already released files without invalidating all checksums.
